import mernStack from "../assets/projects/mern_stack.png";
import pythonDev from "../assets/projects/python_dev.png";
import dsaCoding from "../assets/projects/dsa_coding.png";
import webDev from "../assets/projects/web_dev.png";
import toolsUtils from "../assets/projects/tools_utils.png";

export const projects = [
  {
    title: "Portfolio",
    description: "Personal portfolio website built with React and Tailwind CSS.",
    image: webDev,
    tags: ["React", "Tailwind CSS", "Frontend"],
    liveUrl: "https://github.com/Rampravsh/protfolio",
    githubUrl: "https://github.com/Rampravsh/protfolio",
  },
  {
    title: "Rampravsh",
    description: "MERN Stack Developer | Building scalable web applications with MongoDB, Express, React, and Node.js.",
    image: mernStack,
    tags: ["MERN", "Full Stack", "Profile"],
    liveUrl: "https://github.com/Rampravsh/Rampravsh",
    githubUrl: "https://github.com/Rampravsh/Rampravsh",
  },
  {
    title: "LeetCode Problem",
    description: "Solutions to various LeetCode problems and algorithms.",
    image: dsaCoding,
    tags: ["Algorithms", "Problem Solving", "C++"],
    liveUrl: "https://github.com/Rampravsh/LeetCode-Problem",
    githubUrl: "https://github.com/Rampravsh/LeetCode-Problem",
  },
  {
    title: "C++",
    description: "C++ programming exercises and projects.",
    image: dsaCoding,
    tags: ["C++", "Programming", "OOP"],
    liveUrl: "https://github.com/Rampravsh/cpp",
    githubUrl: "https://github.com/Rampravsh/cpp",
  },
  {
    title: "DSA",
    description: "Data Structures and Algorithms implementation and practice.",
    image: dsaCoding,
    tags: ["DSA", "Algorithms", "Computer Science"],
    liveUrl: "https://github.com/Rampravsh/DSA",
    githubUrl: "https://github.com/Rampravsh/DSA",
  },
  {
    title: "YT Adblocker",
    description: "A browser extension to block advertisements on YouTube.",
    image: toolsUtils,
    tags: ["JavaScript", "Extension", "Utility"],
    liveUrl: "https://github.com/Rampravsh/yt-adblocker",
    githubUrl: "https://github.com/Rampravsh/yt-adblocker",
  },
  {
    title: "Flask",
    description: "Web application projects built with Python Flask framework.",
    image: pythonDev,
    tags: ["Python", "Flask", "Backend"],
    liveUrl: "https://github.com/Rampravsh/flask",
    githubUrl: "https://github.com/Rampravsh/flask",
  },
  {
    title: "Python Project",
    description: "Various Python scripts and small projects.",
    image: pythonDev,
    tags: ["Python", "Scripting", "Automation"],
    liveUrl: "https://github.com/Rampravsh/python-project",
    githubUrl: "https://github.com/Rampravsh/python-project",
  },
  {
    title: "Python",
    description: "General Python programming concepts and examples.",
    image: pythonDev,
    tags: ["Python", "Learning", "Code"],
    liveUrl: "https://github.com/Rampravsh/Python",
    githubUrl: "https://github.com/Rampravsh/Python",
  },
  {
    title: "DSA with GeeksforGeeks",
    description: "Practice problems and solutions from GeeksforGeeks.",
    image: dsaCoding,
    tags: ["DSA", "GeeksforGeeks", "Algorithms"],
    liveUrl: "https://github.com/Rampravsh/DSA-with-GeeksforGeeks",
    githubUrl: "https://github.com/Rampravsh/DSA-with-GeeksforGeeks",
  },
  {
    title: "LMS",
    description: "Learning Management System built with MERN stack.",
    image: mernStack,
    tags: ["MERN", "LMS", "Education"],
    liveUrl: "https://github.com/Rampravsh/lms",
    githubUrl: "https://github.com/Rampravsh/lms",
  },
  {
    title: "MERN Chat App",
    description: "Real-time chat application using MERN stack and Socket.io.",
    image: mernStack,
    tags: ["MERN", "Socket.io", "Real-time"],
    liveUrl: "https://github.com/Rampravsh/MERN-Chat-App",
    githubUrl: "https://github.com/Rampravsh/MERN-Chat-App",
  },
  {
    title: "RegEx",
    description: "Regular Expression learning resources and examples.",
    image: toolsUtils,
    tags: ["RegEx", "Pattern Matching", "Utility"],
    liveUrl: "https://github.com/Rampravsh/RegEx",
    githubUrl: "https://github.com/Rampravsh/RegEx",
  },
  {
    title: "DSA with Procoder",
    description: "DSA concepts learned and practiced with Procoder.",
    image: dsaCoding,
    tags: ["DSA", "Learning", "Code"],
    liveUrl: "https://github.com/Rampravsh/DSA-with-procoder",
    githubUrl: "https://github.com/Rampravsh/DSA-with-procoder",
  },
  {
    title: "JS Chai Aur Code",
    description: "JavaScript learning journey with Chai Aur Code.",
    image: toolsUtils,
    tags: ["JavaScript", "Learning", "Concepts"],
    liveUrl: "https://github.com/Rampravsh/Javascript-chai-aur-code",
    githubUrl: "https://github.com/Rampravsh/Javascript-chai-aur-code",
  },
  {
    title: "React with S4U",
    description: "React web development projects.",
    image: webDev,
    tags: ["React", "Frontend", "Web"],
    liveUrl: "https://github.com/Rampravsh/react-with-s4u",
    githubUrl: "https://github.com/Rampravsh/react-with-s4u",
  },
  {
    title: "Redux Toolkit",
    description: "State management implementation using Redux Toolkit.",
    image: webDev,
    tags: ["Redux", "React", "State Management"],
    liveUrl: "https://github.com/Rampravsh/Redux-Toolkit",
    githubUrl: "https://github.com/Rampravsh/Redux-Toolkit",
  },
  {
    title: "React with Chai",
    description: "Advanced React concepts and projects with Chai Aur Code.",
    image: webDev,
    tags: ["React", "Advanced", "Frontend"],
    liveUrl: "https://github.com/Rampravsh/react-with-chai",
    githubUrl: "https://github.com/Rampravsh/react-with-chai",
  },
  {
    title: "100 Day 100 Project",
    description: "Challenge to build 100 projects in 100 days.",
    image: toolsUtils,
    tags: ["Challenge", "Coding", "Projects"],
    liveUrl: "https://github.com/Rampravsh/100-day-100-project",
    githubUrl: "https://github.com/Rampravsh/100-day-100-project",
  },
  {
    title: "Backend",
    description: "Backend development projects and API implementations.",
    image: mernStack,
    tags: ["Node.js", "Express", "API"],
    liveUrl: "https://github.com/Rampravsh/backend",
    githubUrl: "https://github.com/Rampravsh/backend",
  },
  {
    title: "MongoDB",
    description: "Database design and implementation assignments using MongoDB.",
    image: mernStack,
    tags: ["MongoDB", "Database", "NoSQL"],
    liveUrl: "https://github.com/Rampravsh/mongoDB",
    githubUrl: "https://github.com/Rampravsh/mongoDB",
  },
  {
    title: "React CheckBox",
    description: "Custom checkbox component implementation in React.",
    image: webDev,
    tags: ["React", "Component", "UI"],
    liveUrl: "https://github.com/Rampravsh/13.React-CheckBox",
    githubUrl: "https://github.com/Rampravsh/13.React-CheckBox",
  },
  {
    title: "TypeScript with Chai",
    description: "Learning TypeScript with Chai Aur Code.",
    image: webDev,
    tags: ["TypeScript", "Typed JS", "Learning"],
    liveUrl: "https://github.com/Rampravsh/typeScript-with-chai",
    githubUrl: "https://github.com/Rampravsh/typeScript-with-chai",
  },
  {
    title: "Todo Backend",
    description: "Created with StackBlitz ⚡️",
    image: mernStack,
    tags: ["Node.js", "StackBlitz", "Todo"],
    liveUrl: "https://github.com/Rampravsh/with-stackblitz-todo-backend",
    githubUrl: "https://github.com/Rampravsh/with-stackblitz-todo-backend",
  },
  {
    title: "Next.js Pro Coder",
    description: "Next.js framework projects and experiments.",
    image: webDev,
    tags: ["Next.js", "SSR", "React"],
    liveUrl: "https://github.com/Rampravsh/next-Js-from-pro-coder",
    githubUrl: "https://github.com/Rampravsh/next-Js-from-pro-coder",
  },
  {
    title: "K72",
    description: "Project repository.",
    image: toolsUtils,
    tags: ["Project", "Code"],
    liveUrl: "https://github.com/Rampravsh/k72",
    githubUrl: "https://github.com/Rampravsh/k72",
  },
  {
    title: "Thumbnail Generator",
    description: "Automated thumbnail generation tool.",
    image: webDev,
    tags: ["Tool", "Graphics", "Automation"],
    liveUrl: "https://github.com/Rampravsh/Thumbnail-Generator",
    githubUrl: "https://github.com/Rampravsh/Thumbnail-Generator",
  },
  {
    title: "Blogging Application",
    description: "Full-featured blogging platform.",
    image: mernStack,
    tags: ["MERN", "Blog", "Full Stack"],
    liveUrl: "https://github.com/Rampravsh/Blogging-Application",
    githubUrl: "https://github.com/Rampravsh/Blogging-Application",
  },
  {
    title: "Electron JS",
    description: "Desktop application development using Electron.",
    image: toolsUtils,
    tags: ["Electron", "Desktop", "JavaScript"],
    liveUrl: "https://github.com/Rampravsh/Electron-js",
    githubUrl: "https://github.com/Rampravsh/Electron-js",
  },
  {
    title: "MERN Stack",
    description: "MERN stack resources and starter codes.",
    image: mernStack,
    tags: ["MERN", "Starter", "Web"],
    liveUrl: "https://github.com/Rampravsh/Mern-stack",
    githubUrl: "https://github.com/Rampravsh/Mern-stack",
  },
  {
    title: "MERN Auth",
    description: "Complete authentication system using MERN stack.",
    image: mernStack,
    tags: ["Authentication", "Security", "MERN"],
    liveUrl: "https://github.com/Rampravsh/Complete-MERN-Authentication",
    githubUrl: "https://github.com/Rampravsh/Complete-MERN-Authentication",
  },
  {
    title: "Github Course",
    description: "Notes and resources for mastering Git and GitHub.",
    image: webDev,
    tags: ["Git", "GitHub", "Version Control"],
    liveUrl: "https://github.com/Rampravsh/Github-course",
    githubUrl: "https://github.com/Rampravsh/Github-course",
  },
  {
    title: "NodeJS Streams",
    description: "Deep dive into Node.js streams and data handling.",
    image: mernStack,
    tags: ["Node.js", "Streams", "Backend"],
    liveUrl: "https://github.com/Rampravsh/20.NodeJS-Streams",
    githubUrl: "https://github.com/Rampravsh/20.NodeJS-Streams",
  },
  {
    title: "Socket.IO Messaging",
    description: "Real-time messaging implementation using Socket.io.",
    image: mernStack,
    tags: ["Socket.io", "Real-time", "Chat"],
    liveUrl: "https://github.com/Rampravsh/19.Socket.IO---Real-Time-Messaging",
    githubUrl: "https://github.com/Rampravsh/19.Socket.IO---Real-Time-Messaging",
  },
  {
    title: "My App",
    description: "General application repository.",
    image: webDev,
    tags: ["App", "Web", "General"],
    liveUrl: "https://github.com/Rampravsh/my-app",
    githubUrl: "https://github.com/Rampravsh/my-app",
  },
  {
    title: "Itsrpk",
    description: "Personal repository or configuration.",
    image: toolsUtils,
    tags: ["Personal", "Config"],
    liveUrl: "https://github.com/Rampravsh/itsrpk",
    githubUrl: "https://github.com/Rampravsh/itsrpk",
  },
  {
    title: "Open Source Contribution",
    description: "A repo to contribute in open source via README only.",
    image: webDev,
    tags: ["Open Source", "Contribution", "Community"],
    liveUrl: "https://github.com/Rampravsh/open-source-contribution",
    githubUrl: "https://github.com/Rampravsh/open-source-contribution",
  },
];
